### PR TITLE
transform posts store into map from object

### PR DESCRIPTION
**Pull request by jackdishman**

### CODE REVIEW

**Comment by ldmweb** [comment]
We should add a "no more post" or "no posts in this category" when the fetched posts length is 0
Capture d’écran 2022-09-27 à 15 49 51

**Comment by ldmweb** [comment]
Bookmarks is also supposed to have an empty message
Capture d’écran 2022-09-27 à 15 50 57
on Blogchain:
Capture d’écran 2022-09-27 à 15 51 34

**Comment by ldmweb** [comment]
Add a "no more posts" at the end of the list
Capture d’écran 2022-09-27 à 15 52 38

**Comment by jackdishman** [comment]
> Add a "no more posts" at the end of the posts list on profile page (same on category page, home page and tag page) Capture d’écran 2022-09-27 à 15 52 38

I'll do this once I implement pagination

**Pull request merged**
